/**
  * @Class Name: TriggerGenerationException
  * @Description: This is Helper class to throw an exception when trigger creation fails.
  *  =====================================================================================================
  *       Version   | Date        | Author              | Comments
  *   ----------------------------------------------------------------------------------------------------
  *       1.0       | 16/11/2015  | Eternus Solutions   | 1. This is Helper class to throw an exception
  *                                                          when trigger creation fails.
  *  =====================================================================================================
  **/

/**
  * @Author: Eternus Solutions
  * @Description: Implemented an interface to throw an exception when trigger creation fails.
  * @Param: NA
  * @Return: NA
  * @Date: 22/7/2016
  **/
public with sharing class TriggerGenerationException extends Exception{}